# Generated by Django 5.0.7 on 2024-08-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=85)),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=85)),
                ('city', models.CharField(max_length=85)),
                ('publisher', models.CharField(max_length=85)),
            ],
        ),
    ]
