# Generated by Django 5.0.7 on 2024-08-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0002_books_created_at_books_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
