# Generated by Django 5.0.7 on 2024-08-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0003_alter_books_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
